### ISSUE TITLE
Add a timeout flag ssh_scan

### ISSUE THREAD

**Issue by gallypette** [D4-project/passive-ssh#3]
It would come especially handy when dealing with large lists of hosts:
```
cat ips |  xargs -I {} ./ssh_scan.py --proxy -i 127.0.0.1 -pp 9050 -t {} 
Socket error: 0x05: Connection refused
{}
0.470165491104126
Socket error: timed out
{}
30.028011560440063
Socket error: timed out
{}
30.03199052810669
Socket error: timed out
{}
30.032567501068115
```

**Comment by adulau** [comment]
Indeed but I'm currently scanning pretty large subnet ranges and the timeout seems much lower to me. Not sure from where it's coming from.

**Comment by Terrtia** [comment]
New flag --timeout added d5a7e7e968aae5bcae7910e0d350c20e85095f56
